name: Deployment-Action

on:
  push:
    branches: ["main"]

jobs:
  deploy:

    runs-on: ubuntu-18.04

    steps:
      - name: Checkout source code
        uses: actions/checkout@main

      - name: Set up Node.js
        uses: actions/setup-node@main
        with:
          node-version: 20.x

      - name: Install dependencies
        run: npm install --force

      - name: Build
        run: npm run build

      - name: Deploy to s3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws s3 sync ./dist s3://effi-fe-s3 --region ap-northeast-2

      - name: Invalidate CloudFront Cache 
        run: aws cloudfront create-invalidation --distribution-id ${{secrets.DISTRIBUTION_ID}} --paths "/*"

